basePath: /v1
definitions:
  models.FileModel:
    properties:
      created_at:
        type: string
      creator:
        type: integer
      filename:
        type: string
      filepath:
        type: string
      id:
        type: integer
      size_bytes:
        type: integer
    type: object
  models.PostModel:
    properties:
      created_at:
        type: string
      creator:
        $ref: '#/definitions/models.UserModel'
      description:
        type: string
      files:
        items:
          $ref: '#/definitions/models.FileModel'
        type: array
      id:
        type: integer
      tags:
        items:
          $ref: '#/definitions/models.TagModel'
        type: array
      updated_at:
        type: string
    type: object
  models.ProfileModel:
    properties:
      avatar:
        $ref: '#/definitions/models.FileModel'
      bio:
        type: string
      fullname:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  models.RoleModel:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.TagModel:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.UserModel:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_private:
        type: boolean
      is_verifyed:
        type: boolean
      profile:
        $ref: '#/definitions/models.ProfileModel'
      role:
        $ref: '#/definitions/models.RoleModel'
      updated_at:
        type: string
      username:
        type: string
    type: object
  payloads.CreateFilePayload:
    properties:
      creator:
        type: integer
      filename:
        type: string
      filepath:
        type: string
      size_bytes:
        type: integer
    type: object
  payloads.CreateUserPayload:
    properties:
      avatar:
        $ref: '#/definitions/payloads.CreateFilePayload'
      bio:
        maxLength: 512
        type: string
      email:
        maxLength: 255
        type: string
      fullname:
        maxLength: 255
        minLength: 8
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
      username:
        maxLength: 255
        type: string
    required:
    - email
    - fullname
    - password
    - username
    type: object
  payloads.LoginUserPayload:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 255
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  payloads.UserWithToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.UserModel'
    type: object
host: localhost:4000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: this is a doc for my created apis.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: My Golang Instagram
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: we can login user and return a token
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payloads.LoginUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payloads.UserWithToken'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: we can register new user and return a token
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payloads.CreateUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payloads.UserWithToken'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: create user
      tags:
      - auth
  /posts/new:
    post:
      consumes:
      - multipart/form-data
      description: create a post with multiple files (images/documents) using form-data
      parameters:
      - description: Post description
        in: formData
        name: description
        type: string
      - description: Tags as JSON array e.g. [\
        in: formData
        name: tags
        type: string
      - collectionFormat: csv
        description: Files to upload (1-5 files, max 10MB each)
        in: formData
        items:
          type: file
        name: files
        required: true
        type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.PostModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "413":
          description: Request Entity Too Large
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: create a post with files
      tags:
      - posts
  /users/{postid}:
    get:
      consumes:
      - application/json
      description: get one post by ID
      parameters:
      - description: post ID
        in: path
        name: postid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PostModel'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get single post
      tags:
      - posts
  /users/{userid}:
    get:
      consumes:
      - application/json
      description: get one user by ID
      parameters:
      - description: User ID
        in: path
        name: userid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserModel'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get single user
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: usign the client token we'll give the user which use token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserModel'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get the user in the token
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
